package dev.techie.buy_purchases.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF56650B)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD9EC86)
val md_theme_light_onPrimaryContainer = Color(0xFF181E00)
val md_theme_light_secondary = Color(0xFF5D6148)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE2E5C6)
val md_theme_light_onSecondaryContainer = Color(0xFF1A1D0A)
val md_theme_light_tertiary = Color(0xFF3F665D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC1EBE0)
val md_theme_light_onTertiaryContainer = Color(0xFF00201B)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFCF4)
val md_theme_light_onBackground = Color(0xFF1B1C17)
val md_theme_light_surface = Color(0xFFFFFCF4)
val md_theme_light_onSurface = Color(0xFF1B1C17)
val md_theme_light_surfaceVariant = Color(0xFFE4E3D4)
val md_theme_light_onSurfaceVariant = Color(0xFF46483D)
val md_theme_light_outline = Color(0xFF77786B)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF31312C)
val md_theme_light_inverseOnSurface = Color(0xFFF3F1E9)
val md_theme_light_inversePrimary = Color(0xFFBDCF6D)
val md_theme_light_surfaceTint = Color(0xFF56650B)

val md_theme_dark_primary = Color(0xFFBDCF6D)
val md_theme_dark_onPrimary = Color(0xFF2B3400)
val md_theme_dark_primaryContainer = Color(0xFF3F4C00)
val md_theme_dark_onPrimaryContainer = Color(0xFFD9EC86)
val md_theme_dark_secondary = Color(0xFFC5C9AB)
val md_theme_dark_onSecondary = Color(0xFF2E321D)
val md_theme_dark_secondaryContainer = Color(0xFF454932)
val md_theme_dark_onSecondaryContainer = Color(0xFFE2E5C6)
val md_theme_dark_tertiary = Color(0xFFA6CFC4)
val md_theme_dark_onTertiary = Color(0xFF0D372F)
val md_theme_dark_tertiaryContainer = Color(0xFF274D45)
val md_theme_dark_onTertiaryContainer = Color(0xFFC1EBE0)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFB4AB)
val md_theme_dark_background = Color(0xFF1B1C17)
val md_theme_dark_onBackground = Color(0xFFE5E2DB)
val md_theme_dark_surface = Color(0xFF1B1C17)
val md_theme_dark_onSurface = Color(0xFFE5E2DB)
val md_theme_dark_surfaceVariant = Color(0xFF46483D)
val md_theme_dark_onSurfaceVariant = Color(0xFFC7C7B9)
val md_theme_dark_outline = Color(0xFF919284)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFE5E2DB)
val md_theme_dark_inverseOnSurface = Color(0xFF31312C)
val md_theme_dark_inversePrimary = Color(0xFF56650B)
val md_theme_dark_surfaceTint = Color(0xFFBDCF6D)


val seed = Color(0xFF697921)
